=== Baohong/ATtILA2/ToolboxSource/LandCoverClassifications/LCCSchema_v2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="lcc" xmlns="lcc" xmlns:k="lcc">
  <xs:element name="lccSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="description"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="coefficients">
          <xs:annotation>
            <xs:documentation>
              * The "Coefficients" node contains coefficients to be assigned to values.
              *
              * id - text, unique identifier
              * name - text, name describing coefficient
              * fieldName - text, name of field to be created for output
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="coefficient" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                      <xs:attribute name="Id" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="NITROGEN"/>
                            <xs:enumeration value="PHOSPHORUS"/>
                            <xs:enumeration value="IMPERVIOUS"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute type="xs:string" name="Name" use="required"/>
                      <xs:attribute name="apMethod" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="A"/>
                            <xs:enumeration value="P"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="fieldName" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="values">
          <xs:annotation>
            <xs:documentation>
              * The "values" node defines the full set of values that can exist in a landcover raster
              * The "excluded" attribute is used to exclude values from the total, excluded=false is the default
              * Actual excluded values are always treated as excluded=true, cannot be used in classes, and should not be listed here.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="value" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="coefficient" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Id" use="required"/>
                            <xs:attribute type="xs:decimal" name="value" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="Id" use="required"/>
                  <xs:attribute type="xs:string" name="Name" use="optional"/>
                  <xs:attribute type="xs:boolean" name="excluded" use="optional"/>
                </xs:complexType>
                <xs:unique name="uniqueCoefficient">
                  <xs:selector xpath="coefficient"/>
                  <xs:field xpath="@Id"/>
                </xs:unique>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="classes">
          <xs:annotation>
            <xs:documentation>
              * The "classes" node contains values grouped into classes.
              * A class can contain either values or classes but not both types
              * Values contain only an id which refers to a value in values node.
              * The id attribute is used for the root of the field name in the output(for example %forest would be P + for = Pfor)
              * Two classes with the same id are not allowed.
              * Special class attributes:
              - filter: a string of tool shortnames separated by a ";". If a shortname is provided, that class
              will not appear in the "Report metrics for these classes" section of that particular tool's gui dialog.
              Possible shortnames are: lcp, rlcp, lcosp, splcp, and caeam
              - xxxxField:  if present, it overides the default output field name with the supplied string value. "xxxx" refers
              to a tool's shortname. Possible shortnames are: lcp, rlcp, lcosp, splcp, and caeam
              Example, if lcpField="NINDEX" for the "nat" class, the default output, "pNat" will be overridden with "NINDEX"
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class" maxOccurs="unbounded" minOccurs="1" type="classType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <!--<xs:key name="coefficientKey">
      <xs:selector xpath="k:coefficients/k:coefficient"/>
      <xs:field xpath="@Id"/>
    </xs:key>
    <xs:keyref name="coefficientKeyRef" refer="k:coefficientKey">
      <xs:selector xpath="k:values/k:value/k:coefficient"/>
      <xs:field xpath="@Id"/>
    </xs:keyref>-->
  </xs:element>
  <xs:complexType name="classType">
    <xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="class" maxOccurs="unbounded" minOccurs="0" type="classType"/>
        <xs:element name="value" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute type="xs:int" name="Id" use="required"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Id" use="required"/>
    <xs:attribute type="xs:string" name="Name" use="optional"/>
    <xs:attribute type="xs:string" name="lcpField" use="optional"/>
    <xs:attribute type="xs:string" name="rlcpField" use="optional"/>
    <xs:attribute type="xs:string" name="lcospField" use="optional"/>
    <xs:attribute type="xs:string" name="splcpField" use="optional"/>
    <xs:attribute type="xs:string" name="caeamField" use="optional"/>
    <xs:attribute type="xs:string" name="filter" use="optional"/>
  </xs:complexType>
</xs:schema>

=== Baohong/ATtILA2/ToolboxSource/LandCoverClassifications/CORINE(CLC2006) ALL.xml
<?xml version='1.0' encoding='UTF-8'?>
<lccSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="lcc" xsi:noNamespaceSchemaLocation="LCCSchema_v2.xsd">
    <metadata>
        <name>CORINE (CLC1990) ALL</name>
        <description>CORINE (CLC1990) ALL Land Cover Classification Schema. No raster values except those representing NODATA are excluded from the calculation of reporting unit effective area (i.e., effective area equals the total raster area within a reporting unit).</description>
    </metadata>
    <!--  
        * The coefficients node contains coefficients to be assigned to values.
           
        * REQUIRED ATTRIBUTES
        * Id - text, unique identifier
        * Name - text, word or phrase describing coefficient
        * fieldName - text, name of field to be created for output
        * method - text, "P" or "A", designates "P"ercentage or per unit "A"rea calculation routine
     -->
    <coefficients>
        <coefficient Id="IMPERVIOUS" Name="Percent Cover Total Impervious Area" method="P" fieldName="PCTIA" />
        <coefficient Id="NITROGEN" Name="Estimated Nitrogen Loading Based on Land Cover" method="A" fieldName="N_Load" />
        <coefficient Id="PHOSPHORUS" Name="Estimated Phosphorus Loading Based on Land Cover" method="A" fieldName="P_Load" />
    </coefficients>
    <!--  
        * The values node defines the full set of values that can exist in a land cover raster.
        
        * REQUIRED ATTRIBUTES
        * Id - integer, raster code
        *
        * OPTIONAL ATTRIBUTES
        * Name - text, word or phrase describing value
        * excluded - boolean, "true" or "false" or "1" or "0"
        *          - used to exclude values from effective area calculations
        *          - excluded=false is the default 
        
        * A value element can optionally contain one or more coefficient elements

        * REQUIRED COEFFICIENT ATTRIBUTES
        * Id - text, must match an Id attribute from a coefficients node element
        * value - decimal, weighting/calculation factor
     -->
    <values>
        <value Id="1" Name="111 - Continuous urban fabric">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="2" Name="112 - Discontinuous urban fabric">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="3" Name="121 - Industrial or commercial units">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="4" Name="122 - Road and rail networks and associated land">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="5" Name="123 - Port areas">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="6" Name="124 - Airports">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="7" Name="131 - Mineral extraction sites">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="8" Name="132 - Dump sites">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="9" Name="133 - Construction sites">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="10" Name="141 - Green urban areas">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="11" Name="142 - Sport and leisure facilities">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="9.25" />
            <coefficient Id="PHOSPHORUS" value="1.385" />
        </value>
        <value Id="12" Name="211 - Non-irrigated arable land">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.564" />
            <coefficient Id="PHOSPHORUS" value="0.059" />
        </value>
        <value Id="13" Name="212 - Permanently irrigated land">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="14" Name="213 - Rice fields">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="15" Name="221 - Vineyards">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="16" Name="222 - Fruit trees and berry plantations">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="17" Name="223 - Olive groves">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="18" Name="231 - Pastures">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="19" Name="241 - Annual crops associated with permanent crops">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.0" />
        </value>
        <value Id="20" Name="242 - Complex cultivation patterns">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="21" Name="243 - Land principally occupied by agriculture, with significant areas of natural vegetation">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="11.926" />
            <coefficient Id="PHOSPHORUS" value="0.68" />
        </value>
        <value Id="22" Name="244 - Agro-forestry areas">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="2.447" />
            <coefficient Id="PHOSPHORUS" value="0.089" />
        </value>
        <value Id="23" Name="311 - Broad-leafed forest">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="2.447" />
            <coefficient Id="PHOSPHORUS" value="0.089" />
        </value>
        <value Id="24" Name="312 - Coniferous forest">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="2.447" />
            <coefficient Id="PHOSPHORUS" value="0.089" />
        </value>
        <value Id="25" Name="313 - Mixed forest">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="2.447" />
            <coefficient Id="PHOSPHORUS" value="0.089" />
        </value>
        <value Id="26" Name="321 - Natural grasslands">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.564" />
            <coefficient Id="PHOSPHORUS" value="0.059" />
        </value>
        <value Id="27" Name="322 - Moors and heathland">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.564" />
            <coefficient Id="PHOSPHORUS" value="0.059" />
        </value>
        <value Id="28" Name="323 - Sclerophyllous vegetation">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.564" />
            <coefficient Id="PHOSPHORUS" value="0.059" />
        </value>
        <value Id="29" Name="324 - Transitional woodland-shrub">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.564" />
            <coefficient Id="PHOSPHORUS" value="0.059" />
        </value>
        <value Id="30" Name="331 - Beaches, dunes, sands">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.0" />
            <coefficient Id="PHOSPHORUS" value="0.0" />
        </value>
        <value Id="31" Name="332 - Bare rocks">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.0" />
            <coefficient Id="PHOSPHORUS" value="0.0" />
        </value>
        <value Id="32" Name="333 - Sparsely vegetated areas">
            <coefficient Id="IMPERVIOUS" value="0.0" />
            <coefficient Id="NITROGEN" value="0.0" />
            <coefficient Id="PHOSPHORUS" value="0.0" />
        </value>
